src/Entity/Historique.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HistoriqueRepository")
 */
class Historique
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Membre", inversedBy="historiques")
     * @ORM\JoinColumn(nullable=false)
     */
    private $membre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Media", inversedBy="historiques")
     * @ORM\JoinColumn(nullable=false)
     */
    private $media;

    /**
     * @ORM\Column(type="datetime")
     */
    private $emprunt_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $retour_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $relance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): self
    {
        $this->membre = $membre;

        return $this;
    }

    public function getMedia(): ?Media
    {
        return $this->media;
    }

    public function setMedia(?Media $media): self
    {
        $this->media = $media;

        return $this;
    }

    public function getEmpruntAt(): ?\DateTimeInterface
    {
        return $this->emprunt_at;
    }

    public function setEmpruntAt(\DateTimeInterface $emprunt_at): self
    {
        $this->emprunt_at = $emprunt_at;

        return $this;
    }

    public function getRetourAt(): ?\DateTimeInterface
    {
        return $this->retour_at;
    }

    public function setRetourAt(\DateTimeInterface $retour_at): self
    {
        $this->retour_at = $retour_at;

        return $this;
    }

    public function getRelance(): ?int
    {
        return $this->relance;
    }

    public function setRelance(?int $relance): self
    {
        $this->relance = $relance;

        return $this;
    }
}

src/Entity/Media.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MediaRepository")
 * @Vich\Uploadable
 */
class Media
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $designation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="medias")
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Historique", mappedBy="media", orphanRemoval=true)
     */
    private $historiques;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etagere", inversedBy="media")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etagere;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="medias", fileNameProperty="imageName", size="imageSize")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $imageSize;

    public function __construct()
    {
        $this->historiques = new ArrayCollection();
    }
	
	public function __toString(){
      		return $this->nom;
      	}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(?string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


    /**
     * @return Collection|Historique[]
     */
    public function getHistoriques(): Collection
    {
        return $this->historiques;
    }

    public function addHistorique(Historique $historique): self
    {
        if (!$this->historiques->contains($historique)) {
            $this->historiques[] = $historique;
            $historique->setMedia($this);
        }

        return $this;
    }

    public function removeHistorique(Historique $historique): self
    {
        if ($this->historiques->contains($historique)) {
            $this->historiques->removeElement($historique);
            // set the owning side to null (unless already changed)
            if ($historique->getMedia() === $this) {
                $historique->setMedia(null);
            }
        }

        return $this;
    }

    public function getEtagere(): ?Etagere
    {
        return $this->etagere;
    }

    public function setEtagere(?Etagere $etagere): self
    {
        $this->etagere = $etagere;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile $imageFile
     * @throws
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Service\BibliothequeService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Membre;
use App\Entity\Media;
use App\Entity\Historique;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
	 * @Route("/home", name="home2")
     */
    public function index()
    {
		$membres = $this->getDoctrine()->getRepository(Membre::class)->findAll();
		$medias = $this->getDoctrine()->getRepository(Media::class)->findAll();
		$historique = $this->getDoctrine()->getRepository(Historique::class)->findAll();
        
		return $this->render('home/index.html.twig', [
            'membres' => $membres,
			'medias' => $medias,
			'historiques' => $historique
        ]);
    }

    /**
     * @Route("/test-non-rendu", name="tnr")
     */
    public function test(BibliothequeService $bibliothequeService)
    {
        dd($bibliothequeService->notReturnSendMail($this->getDoctrine()));
        //dd($bibliothequeService->notReturn($this->getDoctrine()->getRepository(Historique::class)));
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block body %}
<div class="container">
    <div class="col">
        <h1>Mon board</h1>
        <div class="col-6">
            <h3>Membres</h3>
            <table>
                <tr>
                <th>nom</th>
                <th class="col-7">inscription</th>
                {% for membre in membres %}
                    <tr>
                        <td><a href='{{ path('membre_show', {'id': membre.id}) }}'>{{ membre.nom }}</a></td>
                        <td class="col-7">{{ membre.createdAt|date('d-m-Y') }}</td>
                    </tr>
                {% endfor %}
                </tr>
                <tr>
                    <td>
                        <a href="{{ path('membre_index') }}">
                            <button class="btn btn-primary">Listing</button>
                        </a>
                    </td>
                </tr>
            </table>
            <h3>Médias</h3>
            <table>
                <th >nom</th>
                <th class="col-7">description</th>
                {% for media in medias %}
                    <tr>
                        <td><a href='{{ path('media_show', {'id': media.id}) }}'>{{ media.nom }}</a></td>
                        <td class="col-7">{{ media.designation }}</td>
                    </tr>
                {% endfor %}
                </tr>
                <tr>
                    <td>
                        <a href="{{ path('media_index') }}">
                            <button class="btn btn-primary">Listing</button>
                        </a>
                    </td>
                </tr>
            </table>
            <h3>Historique</h3>
            <table>
                <th>membre</th>
                <th>media</th>
                <th>début d'emprunt</th>
                <th>fin d'emprunt</th>
                {% for historique in historiques %}
                    <tr>
                        <td>{{ historique.membre }}</td>
                        <td>{{ historique.media }}</td>
                        <td>{{ historique.empruntAt|date('d-m-Y') }}</td>
                        <td>{{ historique.retourAt|date('d-m-Y') }}</td>
                    </tr>
                {% endfor %}
                </tr>
                <tr>
                    <td>
                        <a href="{{ path('historique_index') }}">
                            <button class="btn btn-primary">Listing</button>
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}