src/Entity/Membre.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembreRepository")
 */
class Membre implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $infos;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_pret_auth;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Historique", mappedBy="membre", orphanRemoval=true)
     */
    private $historiques;

    /**
     * @ORM\Column(type="string", length=4096)
     */
    private $password;

    /**
     * @ORM\Column(type="array")
     */
    private $role = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @Assert\Length(max=64, min=8)
     * @Assert\Regex("/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W)/", message="user.assert.password.invalid")
     */
    private $plainPassword;


    public function __construct()
    {
        $this->historiques = new ArrayCollection();
        $this->setRole(['ROLE_SUPER_ADMIN']);
    }
	
	public function __toString(){
        return $this->nom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getInfos(): ?string
    {
        return $this->infos;
    }

    public function setInfos(?string $infos): self
    {
        $this->infos = $infos;

        return $this;
    }

    public function getNbPretAuth(): ?int
    {
        return $this->nb_pret_auth;
    }

    public function setNbPretAuth(int $nb_pret_auth): self
    {
        $this->nb_pret_auth = $nb_pret_auth;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Historique[]
     */
    public function getHistoriques(): Collection
    {
        return $this->historiques;
    }

    public function addHistorique(Historique $historique): self
    {
        if (!$this->historiques->contains($historique)) {
            $this->historiques[] = $historique;
            $historique->setMembre($this);
        }

        return $this;
    }

    public function removeHistorique(Historique $historique): self
    {
        if ($this->historiques->contains($historique)) {
            $this->historiques->removeElement($historique);
            // set the owning side to null (unless already changed)
            if ($historique->getMembre() === $this) {
                $historique->setMembre(null);
            }
        }

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?array
    {
        return $this->role;
    }

    public function setRole(array $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return $this->getRole();
        // TODO: Implement getRoles() method.
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }


    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }
}

src/Entity/Membres.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembresRepository")
 */
class Membres
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('username')
            ->add('plainPassword', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options'  => [
                    'label' => 'change_password.password',
                ],
                'second_options' => [
                    'label' => 'change_password.password_verification',
                ],
            ))
            ->add('nom')
            ->add('infos')
            ->add('nb_pret_auth')
            ->add('created_at')
            ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Form\MembreType;
use App\Form\SearchType;
use App\Repository\MembreRepository;
use App\Service\BibliothequeService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/membre")
 * @Security("has_role('ROLE_USER')")
 */
class MembreController extends AbstractController
{
    /**
     * @Route("/", name="membre_index", methods={"GET"})
     * @Security("has_role('ROLE_SUPER_ADMIN')")
     */
    public function index(Request $request, MembreRepository $membreRepository, BibliothequeService $bibliothequeService): Response
    {
        return $this->render('membre/index.html.twig', [
            'paginate' => $bibliothequeService->paginator($membreRepository, $request->query->get('page', 1),2),
            'membres' => $membreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="membre_new", methods={"GET","POST"})
     * @Security("has_role('ROLE_SUPER_ADMIN') OR has_role('ROLE_MAG')")
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $membre = new Membre();
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $password = $passwordEncoder->encodePassword($form->getData(), $form->getData()->getPlainPassword());
            $form->getData()->setPassword($password);
            $entityManager->persist($membre);
            $entityManager->flush();

            return $this->redirectToRoute('membre_index');
        }

        return $this->render('membre/new.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/search", name="membre_search", methods={"GET","POST"})
     * @Security("has_role('ROLE_SUPER_ADMIN')")
     */
    public function search(Request $request)
    {

        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);
        $results = [];
        if ($form->isSubmitted() && $form->isValid()) {
            $results = $this->getDoctrine()->getRepository(Membre::class)->search($form->getData());
        }

        return $this->render('membre/search.html.twig', [
            'results' => $results,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="membre_show", methods={"GET"})
     */
    public function show(Membre $membre): Response
    {
        return $this->render('membre/show.html.twig', [
            'membre' => $membre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="membre_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Membre $membre): Response
    {
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('membre_index', [
                'id' => $membre->getId(),
            ]);
        }

        return $this->render('membre/edit.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="membre_delete", methods={"DELETE"})
     * @Security("has_role('ROLE_SUPER_ADMIN')")
     */
    public function delete(Request $request, Membre $membre): Response
    {
        if ($this->isCsrfTokenValid('delete' . $membre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($membre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('membre_index');
    }
}

templates/membre/_delete_form.html.twig
<form method="post" action="{{ path('membre_delete', {'id': membre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ membre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/membre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/membre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Membre{% endblock %}

{% block body %}
    <h1>Edit Membre</h1>

    {{ include('membre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('membre_index') }}">back to list</a>

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre index{% endblock %}

{% block body %}
    <h1>Membre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Nom</th>
                <th>Infos</th>
                <th>Nb_pret_auth</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for membre in membres %}
            <tr>
                <td>{{ membre.id }}</td>
                <td>{{ membre.email }}</td>
                <td>{{ membre.nom }}</td>
                <td>{{ membre.infos }}</td>
                <td>{{ membre.nbPretAuth }}</td>
                <td>{{ membre.createdAt ? membre.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ membre.updatedAt ? membre.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('membre_show', {'id': membre.id}) }}">show</a>
                    <a href="{{ path('membre_edit', {'id': membre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('membre_new') }}">Create new</a>
{% endblock %}

templates/membre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Membre{% endblock %}

{% block body %}
    <h1>Create new Membre</h1>

    {{ include('membre/_form.html.twig') }}

    <a href="{{ path('membre_index') }}">back to list</a>
{% endblock %}

templates/membre/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
        <button type="submit">Rechercher</button>
    {{ form_end(form) }}

    <h2>Resultats</h2>

    {% if results|length>0 %}
        <ul>
            {% for Membre in results %}
                <li>{{ Membre }}</li>
            {% endfor %}
        </ul>

    {% else %}No results{% endif %}
{% endblock %}

templates/membre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre{% endblock %}

{% block body %}
    <h1>Membre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ membre.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ membre.email }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ membre.nom }}</td>
            </tr>
            <tr>
                <th>Infos</th>
                <td>{{ membre.infos }}</td>
            </tr>
            <tr>
                <th>Nb_pret_auth</th>
                <td>{{ membre.nbPretAuth }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ membre.createdAt ? membre.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ membre.updatedAt ? membre.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('membre_index') }}">back to list</a>

    <a href="{{ path('membre_edit', {'id': membre.id}) }}">edit</a>

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}